kind: Deployment
apiVersion: apps/v1
metadata:
  name:  nodejs-argo
  annotations:
    description: Defines how to deploy the application server
    template.alpha.openshift.io/wait-for-ready: 'true'
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  replicas: 1
  template:
    metadata:
      name: nodejs-argo
      labels:
        deployment: nodejs
    spec:
      containers:
      - name: nodejs-argo-example
        image: image-registry.openshift-image-registry.svc:5000/ncb-imb/ncb-node-helm
        ports:
        - containerPort: 8080
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/"
            port: 8080
        resources:
          limits:
            memory: '1Gi'
            cpu:  1
  selector:
    matchLabels:
      deployment: nodejs
